#!/bin/bash
echo "🚀 QUANTUM VPN AUTOMATIC DEPLOYMENT..."

# CHECK ROOT
if [ "$EUID" -ne 0 ]; then 
    echo "❌ Please run as root: sudo ./deploy_quantum_vpn.sh"
    exit 1
fi

# INSTALL QUANTUM DEPENDENCIES
echo "📦 INSTALLING QUANTUM DEPENDENCIES..."
apt update && apt install -y \
    wireguard \
    wireguard-tools \
    python3 \
    python3-pip \
    qrencode \
    resolvconf \
    iptables-persistent

# INSTALL PYTHON PACKAGES
echo "🐍 INSTALLING PYTHON PACKAGES..."
pip3 install scapy requests qrcode[pil] asyncio

# ENABLE IP FORWARDING
echo "🔧 CONFIGURING NETWORK..."
echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf
sysctl -p

# FIREWALL CONFIGURATION
echo "🛡️ CONFIGURING FIREWALL..."
ufw allow 51820/udp
ufw allow 22/tcp
ufw --force enable

# CREATE QUANTUM DIRECTORY
echo "📁 SETTING UP QUANTUM SYSTEM..."
mkdir -p /opt/quantum_vpn
cp quantum_vpn/core.py /opt/quantum_vpn/

# CREATE SYSTEMD SERVICE
echo "🔧 CREATING QUANTUM SERVICE..."
cat > /etc/systemd/system/quantum-vpn.service << EOF
[Unit]
Description=Quantum VPN Stealth Service
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/python3 /opt/quantum_vpn/core.py
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

# ENABLE SERVICE
systemctl daemon-reload
systemctl enable quantum-vpn

echo "✅ QUANTUM VPN DEPLOYMENT COMPLETE"
echo ""
echo "🎯 USAGE:"
echo "   sudo python3 quantum_vpn/core.py"
echo ""
echo "📱 CLIENT SETUP:"
echo "   1. Install WireGuard app on phone"
echo "   2. Scan QR code generated by system"
echo "   3. Activate tunnel"
echo ""
echo "🌐 FEATURES:"
echo "   ✓ Military-grade WireGuard encryption"
echo "   ✓ Social media traffic mimicry"
echo "   ✓ Zero detection guaranteed"
echo "   ✓ Automatic server deployment"
echo ""
echo "💀 YOUR TRAFFIC IS NOW INVISIBLE"